# Generated by Django 2.2.1 on 2019-12-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Airbus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='flight_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='user_id',
            field=models.CharField(max_length=30),
        ),
    ]
