# Generated by Django 2.2.1 on 2019-12-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Airbus', '0003_feed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_description',
            field=models.CharField(max_length=10),
        ),
    ]
